### ISSUE TITLE
Hey Josh got some game recommendations 

### ISSUE THREAD

**Issue by JDIZZLE21** [Equinoxx4978/Equinoxx.xyz#2]
Alright i will put them under letters.
P. 
Powerline.io
R.
Runescape
N.
Nobrakes.io
B.
BrowserQuest
E.
Everybody Edits
A.
AdventureQuest 
S.
Slither.io
W.
Worlds Hardest Game
H.
Hexar.io

**Comment by JDIZZLE21** [comment]
+
F.
Flow colors

**Comment by JeffBobGary21** [comment]
Jesus calm down brotha

**Comment by JDIZZLE21** [comment]
DO IT

**Comment by JeffBobGary21** [comment]
Can you give me the links to the games

**Comment by Equinoxx4978** [comment]
- PROGRESS -
✓= Done, - = In progress, ✖ = Can't do, ? = Can't find or Can't find specific one

✓ Browser Quest
✓ Hexar.io
- Powerline.io
- Nobrakes.io
- Slither.io
- Worlds Hardest Game
✖ Everybody Edits
✖ Runescape
? Flow Colors (Too many don't know which one)
